from display.display_config import DisplayConfig
from display.display_window import DisplayWindow
from face_detection.face_detection_config import FaceDetection, FaceDetectionConfig
from video_streams import VideoStreams